const express = require('express');
const multer = require('multer');
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const app = express();
const PORT = process.env.PORT || 3000;
const ROOT = __dirname, DATA_DIR = path.join(ROOT,'data'), UPLOAD_DIR = path.join(ROOT,'uploads');
const CONTENT_FILE = path.join(DATA_DIR,'content.json'), ADMIN_FILE = path.join(DATA_DIR,'admin.json');
fs.mkdirSync(DATA_DIR,{recursive:true}); fs.mkdirSync(UPLOAD_DIR,{recursive:true});
app.use(express.json({limit:'2mb'})); app.use(express.urlencoded({extended:true}));
app.use('/uploads', express.static(UPLOAD_DIR,{maxAge:'7d'})); app.use(express.static(path.join(ROOT,'public')));
const sessions = new Map();
function safe(v){return String(v||'geral').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9_-]/g,'-').slice(0,80)||'geral'}
function readContent(){return JSON.parse(fs.readFileSync(CONTENT_FILE,'utf8'))}
function writeContent(d){fs.writeFileSync(CONTENT_FILE,JSON.stringify(d,null,2))}
function adminOk(req){const t=(req.headers.authorization||'').replace(/^Bearer\s+/i,''); return !!(t&&sessions.has(t))}
function auth(req,res,next){if(!adminOk(req))return res.status(401).json({ok:false,error:'Não autorizado'});next()}
function hash(pass,saltHex){return crypto.scryptSync(String(pass||''),Buffer.from(saltHex,'hex'),32,{N:16384,r:8,p:1}).toString('hex')}
function fileForUrl(url){if(!url||!url.startsWith('/uploads/'))return null; return path.join(UPLOAD_DIR,url.slice('/uploads/'.length))}
function uploadDisk(dir){return multer({storage:multer.diskStorage({destination(req,file,cb){fs.mkdirSync(dir,{recursive:true});cb(null,dir)},filename(req,file,cb){const ext=path.extname(file.originalname).toLowerCase();cb(null,Date.now()+'-'+crypto.randomBytes(5).toString('hex')+ext)}}),limits:{fileSize:550*1024*1024,files:50},fileFilter(req,file,cb){const ok=/^image\/(jpeg|png|webp|gif)$/i.test(file.mimetype)||/^video\/(mp4|webm|quicktime)$/i.test(file.mimetype);cb(ok?null:new Error('Tipo de arquivo não permitido.'))}})}
app.get('/api/content',(req,res)=>{try{res.json(readContent())}catch(e){res.status(500).json({ok:false,error:'Falha ao carregar conteúdo'})}})
app.post('/api/login',(req,res)=>{try{const a=JSON.parse(fs.readFileSync(ADMIN_FILE,'utf8'));const {username,password}=req.body||{};const actual=Buffer.from(hash(password,a.salt),'hex'), expected=Buffer.from(a.hash,'hex');const ok=username===a.username&&actual.length===expected.length&&crypto.timingSafeEqual(actual,expected);if(!ok)return res.status(401).json({ok:false,error:'Usuário ou senha inválidos.'});const token=crypto.randomBytes(32).toString('hex');sessions.set(token,{username,createdAt:Date.now()});res.json({ok:true,token})}catch(e){res.status(500).json({ok:false,error:'Não foi possível entrar.'})}})
app.post('/api/logout',auth,(req,res)=>{const t=(req.headers.authorization||'').replace(/^Bearer\s+/i,'');sessions.delete(t);res.json({ok:true})})
app.post('/api/settings/draft',auth,(req,res)=>{const d=readContent();const s=req.body?.settings||{};d.settings={...d.settings,...s,theme:{...d.settings.theme,...(s.theme||{})},font:{...d.settings.font,...(s.font||{})},hero:{...d.settings.hero,...(s.hero||{})}};writeContent(d);res.json({ok:true,settings:d.settings})})
app.post('/api/settings/publish',auth,(req,res)=>{const d=readContent();d.settings.publishedTheme={...d.settings.theme};d.settings.publishedFont={...d.settings.font};d.settings.hero={...d.settings.hero,published:true};writeContent(d);res.json({ok:true,settings:d.settings})})
app.post('/api/settings/hero',auth,(req,res)=>{const dir=path.join(UPLOAD_DIR,'site');uploadDisk(dir).single('file')(req,res,(err)=>{if(err)return res.status(400).json({ok:false,error:err.message});try{const d=readContent();const old=fileForUrl(d.settings.hero.image);if(old&&fs.existsSync(old))try{fs.unlinkSync(old)}catch{};const f=req.file;if(!f)return res.status(400).json({ok:false,error:'Nenhuma imagem enviada.'});d.settings.hero.image='/uploads/site/'+path.basename(f.path);d.settings.hero.position='center';d.settings.hero.zoom=1;d.settings.hero.published=false;writeContent(d);res.json({ok:true,hero:d.settings.hero})}catch(e){res.status(500).json({ok:false,error:'Falha ao salvar a capa.'})}})})
app.post('/api/events',auth,(req,res)=>{const d=readContent();const {id,name,description}=req.body||{};const sid=safe(id||name);if(!name)return res.status(400).json({ok:false,error:'Nome obrigatório.'});if(d.events.some(e=>e.id===sid))return res.status(409).json({ok:false,error:'Esse evento já existe.'});d.events.push({id:sid,name:String(name).slice(0,80),description:String(description||'').slice(0,300),cover:'',published:true,albums:[]});writeContent(d);res.json({ok:true,data:d})})
app.patch('/api/events/:id',auth,(req,res)=>{const d=readContent(),e=d.events.find(x=>x.id===req.params.id);if(!e)return res.status(404).json({ok:false,error:'Evento não encontrado.'});if(req.body.name!==undefined)e.name=String(req.body.name).slice(0,80);if(req.body.description!==undefined)e.description=String(req.body.description).slice(0,300);if(req.body.cover!==undefined)e.cover=String(req.body.cover);writeContent(d);res.json({ok:true,event:e})})
app.post('/api/albums',auth,(req,res)=>{const d=readContent(),e=d.events.find(x=>x.id===req.body.eventId);if(!e)return res.status(404).json({ok:false,error:'Evento não encontrado.'});const a={id:crypto.randomUUID(),name:String(req.body.name||'Novo álbum').slice(0,100),cover:'',published:false,media:[]};e.albums.push(a);writeContent(d);res.json({ok:true,album:a})})
app.patch('/api/albums/:eventId/:albumId',auth,(req,res)=>{const d=readContent(),a=d.events.find(e=>e.id===req.params.eventId)?.albums.find(x=>x.id===req.params.albumId);if(!a)return res.status(404).json({ok:false,error:'Álbum não encontrado.'});if(req.body.name!==undefined)a.name=String(req.body.name).slice(0,100);if(req.body.cover!==undefined)a.cover=String(req.body.cover);if(Array.isArray(req.body.order)){const map=new Map(a.media.map(m=>[m.id,m]));a.media=req.body.order.map(id=>map.get(id)).filter(Boolean)}writeContent(d);res.json({ok:true,album:a})})
app.post('/api/upload',auth,(req,res)=>{const eventId=safe(req.body.eventId||'outros'),albumId=safe(req.body.albumId||'geral'),dir=path.join(UPLOAD_DIR,eventId,albumId);uploadDisk(dir).array('files',50)(req,res,(err)=>{if(err)return res.status(400).json({ok:false,error:err.message});try{const d=readContent(),a=d.events.find(e=>e.id===req.body.eventId)?.albums.find(x=>x.id===req.body.albumId);if(!a){for(const f of req.files||[])try{fs.unlinkSync(f.path)}catch{};return res.status(404).json({ok:false,error:'Álbum não encontrado.'})}for(const f of req.files||[]){const type=f.mimetype.startsWith('video/')?'video':'image';const url='/uploads/'+eventId+'/'+albumId+'/'+path.basename(f.path);a.media.push({id:crypto.randomUUID(),type,name:f.originalname,url,thumbnail:type==='image'?url:'',published:false,createdAt:new Date().toISOString()})}writeContent(d);res.json({ok:true,count:(req.files||[]).length,album:a})}catch(e){res.status(500).json({ok:false,error:'Falha ao registrar as mídias.'})}})})
app.patch('/api/media/:eventId/:albumId/:mediaId',auth,(req,res)=>{const d=readContent(),a=d.events.find(e=>e.id===req.params.eventId)?.albums.find(x=>x.id===req.params.albumId),m=a?.media.find(x=>x.id===req.params.mediaId);if(!m)return res.status(404).json({ok:false,error:'Mídia não encontrada.'});if(req.body.published!==undefined)m.published=Boolean(req.body.published);if(req.body.name!==undefined)m.name=String(req.body.name).slice(0,120);writeContent(d);res.json({ok:true,media:m})})
app.post('/api/media/bulk-delete',auth,(req,res)=>{const d=readContent(),ids=new Set(req.body?.ids||[]);let removed=0;for(const e of d.events)for(const a of e.albums){const keep=[];for(const m of a.media){if(ids.has(m.id)){const f=fileForUrl(m.url);if(f&&fs.existsSync(f))try{fs.unlinkSync(f)}catch{};removed++}else keep.push(m)}a.media=keep}writeContent(d);res.json({ok:true,removed})})
app.post('/api/media/bulk-publish',auth,(req,res)=>{const d=readContent(),ids=new Set(req.body?.ids||[]);let changed=0;for(const e of d.events)for(const a of e.albums)for(const m of a.media)if(ids.has(m.id)){m.published=Boolean(req.body.published);changed++}writeContent(d);res.json({ok:true,changed})})
app.post('/api/publish-album',auth,(req,res)=>{const d=readContent(),a=d.events.find(e=>e.id===req.body.eventId)?.albums.find(x=>x.id===req.body.albumId);if(!a)return res.status(404).json({ok:false,error:'Álbum não encontrado.'});a.published=true;for(const m of a.media)m.published=true;writeContent(d);res.json({ok:true,album:a})})
app.delete('/api/media/:eventId/:albumId/:mediaId',auth,(req,res)=>{const d=readContent(),a=d.events.find(e=>e.id===req.params.eventId)?.albums.find(x=>x.id===req.params.albumId);if(!a)return res.status(404).json({ok:false,error:'Álbum não encontrado.'});const i=a.media.findIndex(m=>m.id===req.params.mediaId);if(i<0)return res.status(404).json({ok:false,error:'Mídia não encontrada.'});const m=a.media[i],f=fileForUrl(m.url);if(f&&fs.existsSync(f))try{fs.unlinkSync(f)}catch{};a.media.splice(i,1);writeContent(d);res.json({ok:true})})
app.post('/api/quotes',(req,res)=>{const d=readContent();const q={id:crypto.randomUUID(),...req.body,createdAt:new Date().toISOString()};d.quotes.push(q);writeContent(d);res.json({ok:true,quote:q})})
app.get('/api/health',(req,res)=>res.json({ok:true,storage:'disk',content:true,time:new Date().toISOString()}))
app.get('/admin',(req,res)=>res.sendFile(path.join(ROOT,'public','admin.html')))
app.use((req,res,next)=>{ if(req.method==='GET') return res.sendFile(path.join(ROOT,'public','index.html')); next(); })
app.use((err,req,res,next)=>res.status(500).json({ok:false,error:err.message||'Erro interno'}))
app.listen(PORT,()=>console.log('ZINC rodando em http://localhost:'+PORT))
